# Generated by Django 5.1.7 on 2025-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logosvg', models.ImageField(blank=True, null=True, upload_to='final_project_python/')),
            ],
        ),
    ]
