# Generated by Django 5.1.7 on 2025-04-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
